site_name: carlosgrande.me
site_description: Here you'll find my personal life cheat sheet about coding, data architecture, data science, visualization, and business.
repo_url: https://github.com/charlstown/carlos-grande-me
site_author: Charlstown

# Configuration
# Theme
theme:
  name: material
  custom_dir: overrides
  static_templates:
    - 404.html
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.svg
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.path # Path rendered on the upper side
    - navigation.tracking # URL in the address bar is automatically updated with the active anchor in the table of contents.
    - navigation.tabs # Top-level sections are rendered in a menu layer below the header for viewports above
    # - navigation.sections # top-level sections are rendered as groups in the sidebar for viewports above
    - navigation.tabs # Documents can be directly attached to sections
    - navigation.footer
    - navigation.top # A back-to-top button can be shown when the user, after scrolling down, starts to scroll up again
    # - navigation.expand # Expand by default
    #- toc.integrate # Table of contents is always rendered as part of the navigation sidebar on the left.
    - search.suggest
    - search.highlight
    - content.code.copy # Codeblocks
    - content.tabs.link
    - navigation.indexes # Documents attached to sections
  language: en

  # Color palette
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

# Extensions
markdown_extensions:
  - abbr
  - admonition            # Block elements
  - pymdownx.details      # Collapsible call-outs
  - pymdownx.superfences  # Nested elements
  - pymdownx.mark         # Hihlighting text
  - attr_list             # To add buttons
  - md_in_html            # To add html in markdown (centred images)
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:  # Katex library math
      generic: true

# Hooks
hooks:
  - hooks/generate_pages.py
  - hooks/ignore_file_autoreload.py

# Plugins
plugins:
  - search
  - markdownextradata
  - awesome-pages
  - glightbox:
      touchNavigation: true
      loop: true
      effect: zoom
      slide_effect: fade
      width: 100%
      height: auto
      zoomable: false
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

# css
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/output_code.css
  - assets/stylesheets/gallery.css
  - https://unpkg.com/katex@0/dist/katex.min.css  # Katex Math
  - assets/stylesheets/my_katex.css

# javascript
extra_javascript:
  - assets/javascripts/extra.js
  - assets/javascripts/image_caption.js
  - assets/javascripts/output_code.js
  - assets/javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - assets/javascripts/publications.js

# Copyright message
copyright: Copyright &copy; carlosgrande.me - 2025

# Global variables
extra:
  links:
    self-host: 'url'
    learning-host: 'url'
