name: Build + Deploy docs
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'overrides/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'overrides/**'
      - '.github/workflows/**'
jobs:
  main:
    name: Build + Deploy
    runs-on: ubuntu-latest
    steps:
      # checkout this repo
      - name: Checkout repo # Name of the step
        uses: actions/checkout@v4 # Action to run
      - name: Set up Python # Name of the step
        uses: actions/setup-python@v5 # Action to run
        with: # Inputs for the action
          python-version: 3.9 # Version of Python to use
      - name: Install dependencies # Name of the step
        run: | # Command to run
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            python -m mkdocs build
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # The role ARN to assume via OpenID Connect (GitHub OIDC)
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Synchronize files with S3 bucket
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          aws s3 sync site/ s3://$S3_BUCKET/ --delete
